set encoding=utf-8
scriptencoding utf-8
set nocompatible

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

call plug#begin("~/.vim/bundle")

if (!has('nvim'))
    Plug 'noahfrederick/vim-neovim-defaults'
endif

Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-fugitive'
Plug 'w0rp/ale'
Plug 'scrooloose/nerdtree'
Plug 'majutsushi/tagbar'
Plug 'pangloss/vim-javascript'
Plug 'joshdick/onedark.vim'
Plug 'digitaltoad/vim-jade'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-markdown'
Plug 'Raimondi/delimitMate'
Plug 'vim-scripts/camelcasemotion'
Plug 'Yggdroot/indentLine'
Plug 'editorconfig/editorconfig-vim'
Plug 'elzr/vim-json'
Plug 'SirVer/ultisnips'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mustache/vim-mustache-handlebars'
Plug 'airblade/vim-rooter'
Plug 'wting/rust.vim'
Plug 'janko-m/vim-test'
Plug 'mxw/vim-jsx'
Plug 'reedes/vim-pencil'
Plug 'jszakmeister/vim-togglecursor'
Plug 'embear/vim-localvimrc'
Plug 'reedes/vim-colors-pencil'
Plug 'StanAngeloff/php.vim'
Plug 'jparise/vim-graphql'
Plug 'airblade/vim-gitgutter'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'leafgarland/typescript-vim'
Plug 'ekalinin/Dockerfile.vim'

Plug 'Shougo/echodoc.vim'
Plug 'Shougo/neopairs.vim'

if has('nvim')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }
else
    Plug 'Shougo/deoplete.nvim'
    Plug 'autozimu/LanguageClient-neovim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
endif

call plug#end()

filetype plugin on
filetype plugin indent on

set number
set relativenumber

set tabstop=4
set shiftwidth=4
set shiftround
set expandtab
set smartindent
set clipboard=unnamed

set columns=120

" persistent undo
set undofile
set undodir=~/.vim/undodir
set undolevels=1000
set undoreload=10000

" don't show scrollbars, toolbar, menu
set guioptions+=rlTm
set guioptions-=rlTm

"color scheme
set termguicolors
colorscheme onedark

" define a group for autocommands
augroup vimrc
    autocmd!

    " Tabstop 2 for some files
    autocmd FileType yaml setlocal tabstop=2 shiftwidth=2
    autocmd FileType json setlocal tabstop=2 shiftwidth=2
    autocmd FileType coffee setlocal tabstop=2 shiftwidth=2
    autocmd FileType jade setlocal tabstop=2 shiftwidth=2
    autocmd FileType ruby setlocal tabstop=2 shiftwidth=2

    " jshint
    autocmd BufNewFile,BufRead .jshintrc set ft=json

    " bower
    autocmd BufNewFile,BufRead .bowerrc set ft=json

    " CocoaPods
    autocmd BufNewFile,BufRead Podfile,*.podspec      set filetype=ruby

    autocmd FileType markdown call StartMarkdownMode()

augroup END

" Key maps
let g:mapleader=","
noremap <leader>f <esc>:Files<cr>
nnoremap <leader>b <esc>:Buffers<cr>
noremap <leader>g <esc>:Ag<cr>
nnoremap <leader>n :NERDTreeToggle<cr>
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
nnoremap <leader>t :TagbarToggle<cr>
noremap <C-Left> <esc>:tabprevious<cr>
noremap <C-h> <esc>:tabprevious<cr>
noremap <C-Right> <esc>:tabnext<cr>
noremap <C-l> <esc>:tabnext<cr>
nnoremap H ^
nnoremap L $
nnoremap Q <nop>
nnoremap <esc> :noh<return><esc>

" Hard mode
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Abbriviations
iabbrev filed field
iabbrev Filed Field

" case-insensitive :w
command! W normal :w

" indentLine
let g:indentLine_color_gui = '#585858'
let g:indentLine_color_term = 239
let g:indentLine_char = '┊'

" markdown code highlight
let g:markdown_fenced_languages = [
    \ 'javascript',
    \ 'js=javascript',
    \ 'php',
    \ 'graphql',
    \ 'json'
\ ]

" Ultisnpips keys
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsListSnippets = '<s-tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<c-tab>'

" airline
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline#extensions#tagbar#enabled = 0
let g:airline_exclude_preview = 0
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

" ale
let g:ale_linters = {
\   'javascript': ['eslint', 'flow'],
\}

let g:ale_sign_error = '✘'
let g:ale_sign_warning = '⚠'
" no-conceal cursor for indent line
let g:indentLine_noConcealCursor=""

" no conceal for json
let g:vim_json_syntax_conceal = 0

" Vim test mapping
nmap tn :TestNearest<CR>
nmap tt :TestLast<CR>

" Text Width for pencil
let g:pencil#textwidth = 80

" NERDTree
let g:NERDTreeQuitOnOpen = 1

" Vim rooter
let g:rooter_use_lcd = 1

" enable jsx in js files
let g:jsx_ext_required = 0

" enable flow syntax
let g:javascript_plugin_flow = 1

" gitgutter
let g:gitgutter_sign_added = '█'
let g:gitgutter_sign_modified = '█'
let g:gitgutter_sign_removed = '█'
let g:gitgutter_sign_removed_first_line = '-'
let g:gitgutter_sign_modified_removed = '█'

" deoplete
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_camel_case = 1
let g:neopairs#enable = 1
set cmdheight=2
let g:echodoc_enable_at_startup = 1

" Allow to pick completion with arrow keys
inoremap <expr><Down> pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr><Up> pumvisible() ? "\<C-p>" : "\<Up>"

" Language Client settings
let g:LanguageClient_serverCommands = {}
if executable('javascript-typescript-stdio')
    let g:LanguageClient_serverCommands.javascript = ['javascript-typescript-stdio']
    let g:LanguageClient_serverCommands['javascript.jsx'] = ['javascript-typescript-stdio']
else
  echo "javascript-typescript-langserver is not installed!\n"
endif

let g:LanguageClient_autoStart = 1

" Neovim-specific settings
if has('nvim')
    augroup nvimrc
        autocmd!
        autocmd WinEnter term://* startinsert
    augroup END

    set inccommand=split
endif

if filereadable('~/.vim/vimrc.local')
    source '~/.vim/vimrc.local'
endif

function! StartMarkdownMode()
    call pencil#init({'wrap': 'hard'})
    colorscheme pencil
    setlocal background=light
    setlocal spell
    setlocal spelllang=en_us,ru_ru
endfunction

function! EditAlternate()
    let name = StripAllExtensions(expand('%:t'))
    call fzf#vim#files('', {
    \  'source': 'ag -g ' . shellescape(name),
    \ })
endfunction

function! StripAllExtensions(filename)
    let name = a:filename
    let noext = fnamemodify(name, ':r')
    while name != noext
        let name = noext
        let noext = fnamemodify(name, ':r')
    endwhile
    return name
endfunction

nnoremap <C-8> :call EditAlternate()<cr>

